version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: odin_vault_db
    environment:
      POSTGRES_DB: odin_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: odin_vault_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/odin_vault
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 7d
      AWS_ACCESS_KEY_ID: your-access-key
      AWS_SECRET_ACCESS_KEY: your-secret-key
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: your-bucket-name
      PORT: 3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      MAX_FILE_SIZE: 104857600
      ALLOWED_FILE_TYPES: image/*,video/*,application/pdf,text/*,application/json,application/xml
      TRASH_PURGE_DAYS: 30
      DEFAULT_SHARE_EXPIRY_DAYS: 7
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
